# Generated by Django 5.0.4 on 2024-05-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=256, verbose_name='Отчество')),
                ('is_main', models.BooleanField(verbose_name='Главный?')),
                ('role', models.CharField(max_length=256, verbose_name='Роль')),
                ('sex', models.CharField(max_length=20, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('middlename', models.CharField(max_length=256, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_serial', models.CharField(max_length=12, verbose_name='Серия')),
                ('passport_number', models.CharField(max_length=12, verbose_name='Номер')),
                ('passport_getted_by', models.CharField(max_length=255, verbose_name='Выдан')),
                ('passport_getted_date', models.DateField(verbose_name='Дата выдачи')),
                ('birthday_date', models.DateField(verbose_name='День рождения')),
                ('birthday_place', models.CharField(max_length=255, verbose_name='Место рождения')),
                ('registration_adress', models.CharField(max_length=255, verbose_name='Адрес регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Примечание')),
                ('type_of_building', models.CharField(max_length=255, verbose_name='Тип домовладения')),
                ('type_of_city', models.CharField(max_length=255, verbose_name='Тип населенного пункта')),
                ('region', models.CharField(max_length=255, verbose_name='Область')),
                ('street_type', models.CharField(max_length=255, verbose_name='Тип улицы')),
                ('area', models.CharField(max_length=255, verbose_name='Район')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('house', models.CharField(max_length=255, verbose_name='Дом')),
                ('room', models.CharField(blank=True, max_length=255, verbose_name='Квартира или часть дома')),
                ('postcode', models.CharField(max_length=50, verbose_name='Индекс')),
                ('show_part', models.BooleanField(blank=True, verbose_name='Отображать часть дома в документах')),
                ('gas_date', models.DateField(blank=True, verbose_name='Дата пуска газа')),
                ('clients', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gas.client', verbose_name='Ключевые лица')),
                ('contracts', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gas.contract', verbose_name='Договоры')),
                ('passport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gas.passport')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='phones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.phone', verbose_name='Номера телефонов'),
        ),
    ]
