# Generated by Django 5.0.4 on 2024-05-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_alter_object_comment_alter_object_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='gas_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пуска газа'),
        ),
    ]
