# Generated by Django 5.0.4 on 2024-06-30 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0002_alter_contract_date_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 23, 11, 35, 898243), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='objectdevice',
            name='date_of_commissioning',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 23, 11, 35, 899244), verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='objectdevice',
            name='date_of_manufacture',
            field=models.DateField(default=datetime.datetime(2024, 6, 30, 23, 11, 35, 899244), verbose_name='Дата изготовления'),
        ),
    ]
