# Generated by Django 5.0.4 on 2024-05-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0003_alter_object_gas_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gas.client', verbose_name='Ключевые лица'),
        ),
        migrations.AlterField(
            model_name='object',
            name='contracts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gas.contract', verbose_name='Договоры'),
        ),
        migrations.AlterField(
            model_name='object',
            name='show_part',
            field=models.BooleanField(blank=True, null=True, verbose_name='Отображать часть дома/квартиру в документах'),
        ),
    ]
