# Generated by Django 5.0.4 on 2024-06-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0006_rename_passport_getted_by_passport_getted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas.passport'),
        ),
    ]
