# Generated by Django 5.0.4 on 2024-06-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0007_alter_object_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='object',
        ),
        migrations.AddField(
            model_name='object',
            name='clients',
            field=models.ManyToManyField(to='gas.client', verbose_name='Клиенты'),
        ),
    ]
