# Generated by Django 5.0.4 on 2024-06-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0008_remove_client_object_object_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Ответственное лицо?'),
        ),
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(default='Собственник', max_length=256, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('woman', 'Женский'), ('man', 'Мужской')], max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='object',
            name='type_of_building',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира')], max_length=255, verbose_name='Тип домовладения'),
        ),
    ]
