# Generated by Django 5.0.4 on 2024-07-02 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0008_alter_contract_date_of_contract_alter_object_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.DateField(default=datetime.datetime(2024, 7, 2, 23, 9, 57, 395945), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='object',
            name='street_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип улицы'),
        ),
        migrations.AlterField(
            model_name='objectdevice',
            name='date_of_commissioning',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 2, 23, 9, 57, 396947), null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='objectdevice',
            name='date_of_manufacture',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 2, 23, 9, 57, 396947), null=True, verbose_name='Дата изготовления'),
        ),
    ]
