# Generated by Django 5.0.4 on 2024-06-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0009_alter_client_is_main_alter_client_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='clients',
        ),
        migrations.AddField(
            model_name='client',
            name='object',
            field=models.ManyToManyField(to='gas.object', verbose_name='Объект'),
        ),
    ]
