# Generated by Django 5.0.4 on 2024-06-23 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0011_remove_client_object_client_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='passport',
        ),
        migrations.AddField(
            model_name='passport',
            name='object',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='gas.object', verbose_name='Объект'),
            preserve_default=False,
        ),
    ]
