# Generated by Django 5.0.4 on 2024-06-23 12:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0012_remove_object_passport_passport_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 15, 12, 9, 357198), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gas.object'),
        ),
        migrations.AlterField(
            model_name='object',
            name='room',
            field=models.CharField(blank=True, max_length=255, verbose_name='Квартира'),
        ),
    ]
