# Generated by Django 5.0.4 on 2024-06-23 12:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0013_price_alter_contract_date_alter_contract_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 15, 33, 9, 39508), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gas.client'),
        ),
        migrations.CreateModel(
            name='ObjectDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gas.devicemodel', verbose_name='Модель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gas.devicetype', verbose_name='Тип')),
            ],
        ),
    ]
