# Generated by Django 5.0.4 on 2024-07-03 19:09

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0013_alter_contract_date_of_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 22, 9, 52, 826317), verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('act_number', models.IntegerField(verbose_name='Номер')),
                ('uuid_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_act', models.DateField(default=datetime.datetime(2024, 7, 3, 22, 9, 52, 826317), verbose_name='Дата')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gas.master')),
                ('object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gas.object')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
        migrations.CreateModel(
            name='ActPosition',
            fields=[
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('uuid_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_act', models.DateField(default=datetime.datetime(2024, 7, 3, 22, 9, 52, 826317), verbose_name='Дата')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gas.act')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договора',
            },
        ),
    ]
