# Generated by Django 5.0.4 on 2024-06-23 12:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0014_devicemodel_devicetype_alter_contract_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdevice',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gas.object'),
        ),
        migrations.AddField(
            model_name='price',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gas.devicetype', verbose_name='Тип оборудования'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 15, 41, 42, 548750), verbose_name='Дата'),
        ),
    ]
