# Generated by Django 5.0.4 on 2024-07-03 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0014_alter_contract_date_of_contract_act_actposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name': 'Акт', 'verbose_name_plural': 'Акты'},
        ),
        migrations.RemoveField(
            model_name='act',
            name='summ',
        ),
        migrations.RemoveField(
            model_name='actposition',
            name='date_of_act',
        ),
        migrations.RemoveField(
            model_name='actposition',
            name='uuid_number',
        ),
        migrations.AddField(
            model_name='act',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Сумма акта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actposition',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actposition',
            name='name',
            field=models.CharField(default=1, max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actposition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='act_number',
            field=models.CharField(max_length=256, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='act',
            name='date_of_act',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 23, 41, 3, 301190), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='act',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gas.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_of_contract',
            field=models.DateField(default=datetime.datetime(2024, 7, 3, 23, 41, 3, 301190), verbose_name='Дата'),
        ),
    ]
