# Generated by Django 5.0.4 on 2024-06-23 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0015_objectdevice_object_price_type_alter_contract_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='number',
            new_name='contract_number',
        ),
        migrations.RenameField(
            model_name='passport',
            old_name='number',
            new_name='passport_number',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='number',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 16, 19, 58, 222872), verbose_name='Дата'),
        ),
    ]
