# Generated by Django 5.0.6 on 2024-06-23 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas', '0016_rename_number_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.IntegerField(unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 23, 19, 3, 44, 649606), verbose_name='Дата'),
        ),
    ]
